[workspace]

members = [
    "hello_cargo",
    "guess_game",
    "data_types",
    "divisible_not",
    "reverse_num",
    "dna_rna",
    "gen_int",
    "bmi_cal",
    "if_else",
    "return_string",
    "repeat_str",
    "remove_char"
]
